import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./(components)/Navbar/Navbar";
import myUser from "./actions/getUser";
import getBasketItems from "./actions/getBasketItems";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const myCurrentUser = await myUser();

  const basketItems = await getBasketItems();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar myUser={myCurrentUser} basketItems={basketItems} />
        {children}
      </body>
    </html>
  );
}
